version: '3.5'

services:
    postgres:
        container_name: postgres_container
        build:
            context: .
            dockerfile: Dockerfile.postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: ${PGDATA}
        volumes:
            - postgres:${PGDATA}
        ports:
            - '${DB_PORT}:5432'
        networks:
            - postgres
        restart: unless-stopped

    redis:
        container_name: redis_container
        build:
            context: .
            dockerfile: Dockerfile.redis
        ports:
            - '${REDIS_PORT}:6379'

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
    redis:
