export type Environment = {
    NODE_ENV: 'NODE_ENV';
    JWT_SECRET: 'JWT_SECRET';
    JWT_EXPIRE: 'JWT_EXPIRE';
    EMAIL_HOST: 'EMAIL_HOST';
    EMAIL_USER: 'EMAIL_USER';
    EMAIL_PASSWORD: 'EMAIL_PASSWORD';
    REDIS_HOST: 'REDIS_HOST';
    REDIS_PORT: 'REDIS_PORT';
    REDIS_PASSWORD: 'REDIS_PASSWORD';
    CONFIRM_TIME: 'CONFIRM_TIME';
};
