export type Environment = {
    NODE_ENV: 'NODE_ENV';
    JWT_SECRET: 'JWT_SECRET';
    JWT_EXPIRE: 'JWT_EXPIRE';
    EMAIL_HOST: 'EMAIL_HOST';
    EMAIL_USER: 'EMAIL_USER';
    EMAIL_PASSWORD: 'EMAIL_PASSWORD';
    REDIS_URL: 'REDIS_URL';
    CONFIRM_TIME: 'CONFIRM_TIME';
};
